org: benoitbo
app: todos
service: api

plugins:
  - serverless-appsync-plugin
  - serverless-appsync-simulator
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 5
  region: eu-west-1
  memorySize: 512
  stage: ${opt:stage, 'dev'}

  environment:
    STAGE: ${self:provider.stage}
    TODO_TABLE: !Ref TodoTable

custom:
  appSync: ${file(templates/appsync.yml)}
  appsync-simulator:
    apiKey: '1234567890'
  dynamodb:
    stages:
      - dev
    start:
      dbPath: '.dynamodb'
      migrate: true

resources:
  - ${file(templates/dynamodb.yml)}
