name: ${self:provider.stage}-todo
authenticationType: API_KEY

substitutions:
  todosTable: !Ref TodoTable

apiKeys:
  - name: App
    expiresAfter: 365d

logConfig:
  level: ALL

dataSources:
  - type: AMAZON_DYNAMODB
    name: todos
    config:
      tableName:
        Ref: TodoTable

mappingTemplates:
  - dataSource: todos
    type: Mutation
    field: createTodo
  - dataSource: todos
    type: Mutation
    field: addTask
  - dataSource: todos
    type: Query
    field: todos
  - dataSource: todos
    type: Query
    field: todo
  - dataSource: todos
    type: Todo
    field: tasks
