name: ${self:provider.stage}-todo
authenticationType: API_KEY

substitutions:
  todosTable: !Ref TodoTable

apiKeys:
  - name: App
    expiresAfter: 365d

logConfig:
  level: ALL

dataSources:
  - type: AMAZON_DYNAMODB
    name: todos
    config:
      tableName:
        Ref: TodoTable


functionConfigurations:
  - name: findTodo
    dataSource: todos
  - name: deleteTodo
    dataSource: todos

mappingTemplates:
  - dataSource: todos
    type: Mutation
    field: createTodo
  - dataSource: todos
    type: Mutation
    field: addTask
  - dataSource: todos
    type: Mutation
    field: updateTodo
  - dataSource: todos
    type: Mutation
    field: updateTask
  - dataSource: todos
    type: Mutation
    field: deleteTask
  - dataSource: todos
    kind: PIPELINE
    type: Mutation
    field: deleteTodo
    functions:
      - findTodo
      - deleteTodo
  - dataSource: todos
    type: Query
    field: todos
  - dataSource: todos
    type: Query
    field: todo
  - dataSource: todos
    type: Todo
    field: tasks
